name: build and deploy portofolio
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean & Stop Old Service
        run: |
          docker compose down --remove-orphans || docker compose down --remove-orphans || true

      - name: Build and Start Multi-Container App
        run: |
          docker compose up -d --build --force-recreate || docker compose up -d --build --force-recreate
